npm install --save jsonformatter
npm install --save ng2-json-editor
npm install --save ng2-pdf-viewer
npm install --save pdfjs-dist
npm install --save pouchdb
npm install --save xml2js
npm install --save chance
npm install --save chart.json
npm install --save @ionic/storage